### ISSUE TITLE
How to use the model trained from scratch to get aggregated sentence embedding from all the layers 

### ISSUE THREAD

**Issue by shikhar26** [PrashantRanjan09/Elmo-Tutorial#1]
hello, i was able to train my model from scratch and was able to generate my weights file. Problem statement is to calculate the cosine similarity between sentence embedding. Please suggest the method to consume my model that gives us an aggregated result from all the layers in form of embedding for a sentence.
we used https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-interactively but the output embedding we receive is a tensor containing output from each layer of the ELMO model (which are 3) and contains vectors for each word in the sentence rather then the sentence as a whole.

**Comment by PrashantRanjan09** [comment]
@shikhar26 : since you have the vectors, the sentence representation can be an average sum of the vectors along an axis or a weighted sum. You just have to figure out how can you take sum of those vectors along an axis. I don't think thats an issue with the repository. 
However, take a look at this: <https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum>
It might help.
