### ISSUE TITLE
Incremental training on ELMo

### ISSUE THREAD

**Issue by mchari** [PrashantRanjan09/Elmo-Tutorial#5]
Hi,
   I am trying to follow the instructions under (https://github.com/PrashantRanjan09/Elmo-Tutorial/ ) on incremental training. My question is : How do I know which layer to exclude ? 

Thanks!

**Comment by PrashantRanjan09** [comment]
@mchari : Sorry, for the delay in response- but i think *op.name for op in tf.get_default_graph().get_operations()* command should solve your problem. You can give it a try. Generally its the embedding layer which might cause a problem due to different vocab and consequently in session graph restoring mismatch.

I am closing this issue for now.
